# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # - name: Stop IIS
    #   run: Stop-Website -Name "GITHUB_TEST"

    # - name: Start IIS
    #   run: Start-Website -Name "GITHUB_TEST"

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install fresh dependencies  
      run: npm ci

    # - name: Install dependencies
    #   run: npm install
      
    - name: Run the tests
      run: npm test
      
    - name: Build
      run: npm run build

    - name: Copy files to production folder
      run: copy-Item -Path "\GithubRunner\projects\github_action_test\github_action_test\build\" -Destination "\GithubRunner\projects\github_action_test\production_build" -Recurse -force

    # - name: Stop IIS
    #   run: Stop-Website -Name "GITHUB_TEST"

    # - name: Start IIS
    #   run: Start-Website -Name "GITHUB_TEST"